version: "3"
services:
  application_showcase:
    build: .
    command:
      - /start.sh
    container_name: ${APP_CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    entrypoint:
      - /entrypoint.sh
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
      - UWSGI_INI=/app/uwsgi.ini
      - UWSGI_CHEAPER=2
      - UWSGI_PROCESSES=16
      - NGINX_MAX_UPLOAD=0
      - NGINX_WORKER_PROCESSES=1
      - LISTEN_PORT=80
      - ALPINEPYTHON=python3.8
      - STATIC_URL=/static
      - STATIC_PATH=/var/www/app/static
      - STATIC_INDEX=0
      - PYTHONPATH=/app
    hostname: af39222d8bd2
    ipc: private
    logging:
      driver: json-file
      options: {}
    ports:
      - ${APP_TARGET_PORT}:80/tcp
    volumes:
      - ./../TestApp:/app
    working_dir: /app