name: Pytest in Docker
# workflow triggered by any push on any branch
on: [push]
jobs:
  build:
    name: Test container with pytest
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    # runs within your Docker container
    container:
      image: docker://nixonixon/devops_project:0.0.1
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
    - uses: actions/checkout@v2
    - name: pytest functional test
      run: |
          pytest tests/functional.py
